[SETTING]
Version="A76XX_A79XX_MADL V1.32 Only for Update"
PlateForm=1
EraseAll=0
Reboot=0
PowerDown=0
ExitFactoryMode=1
SingleMode=0
EraseCust_data=1
NeedEnterFactoryMode=0
;RebootCmd="at+bootldr=1"
RebootCmd="at$mydownload=1"
;RebootCmd="at+bootldr"
WriteNvmFile=0
NvmFileList="audio_ve.nvm audio_gain.nvm"
MDBFileName="MDB0.txt"
;SendAudioAT="AT*MRD_CDF=U,audio_gain.nvm AT*MRD_CDF=U,audio_voice_calibration.nvm"
SendAudioAT="ATI AT"
AutoConfigAtPort=1
AutoStop=0

[Package_Setting_1802]
Package_File=D:\Firmware\ASR\1828\A7908M220240428\A7908_Nand_Update.blf

[Package_Setting_1601]
Package_File=C:\Users\Administrator\Desktop\819F.zip



[BootLoader_USB_Settings_1802]
Total_USB_Port_Num=0
0_USB_PortAddress=PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(3)
1_USB_PortAddress=PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(12)
2_USB_PortAddress=PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(9)
3_USB_PortAddress=PCIROOT(0)#PCI(1400)#USBROOT(0)#USB(12)


[BootLoader_USB_Settings_1601]
Total_USB_Port_Num=1
0_USB_PortAddress=Port_#0001.Hub_#0003
1_USB_PortAddress=Port_#0012.Hub_#0001
2_USB_PortAddress=Port_#0004.Hub_#0001
3_USB_PortAddress=Port_#0009.Hub_#0001

[ATPORT]
0_ATPORT=0
1_ATPORT=0
2_ATPORT=0
3_ATPORT=0
4_ATPORT=0
5_ATPORT=0
6_ATPORT=0
7_ATPORT=0
8_ATPORT=0
9_ATPORT=0
10_ATPORT=0
11_ATPORT=0
12_ATPORT=0
13_ATPORT=0
14_ATPORT=0
15_ATPORT=0
16_ATPORT=0
17_ATPORT=0
18_ATPORT=0
19_ATPORT=0

[DIAGPORT]
0_DIAGPORT=0
1_DIAGPORT=0
2_DIAGPORT=0
3_DIAGPORT=0
4_DIAGPORT=0
5_DIAGPORT=0
6_DIAGPORT=0
7_DIAGPORT=0
8_DIAGPORT=0
9_DIAGPORT=0
10_DIAGPORT=0
11_DIAGPORT=0
12_DIAGPORT=0
13_DIAGPORT=0
14_DIAGPORT=0
15_DIAGPORT=0
16_DIAGPORT=0
17_DIAGPORT=0
18_DIAGPORT=0
19_DIAGPORT=0

[ColumnWith_Settings]
DeviceState_ColumnWith=70
DeviceIndex_ColumnWith=70
DeviceAddress_ColumnWith=450
DownloadProgress_ColumnWith=400
ElapsedTime_ColumnWith=158
StatusMsg_ColumnWith=349

[UserGuide_Setting]
UserGuideDoc= 

[用户信息设置]
当前工作站=DL
产品信息=A7600_A7900

[User_Info_Settings]
Current_WorkStation_Info=
Product_Info=
